import fs from 'node:fs';
import path from 'node:path';

/**
 * Rule parsers taken from a tool's installed bundle, so a render is checked
 * against the code that reads it (#946). The bundles are not vendored: point
 * `TEAMAI_RULE_PARSER_BUNDLES` at them, as `<tool>=<path>` entries separated
 * by the platform's path delimiter, e.g.
 *
 *   TEAMAI_RULE_PARSER_BUNDLES=cursor=$HOME/.local/share/cursor-agent/versions/<v>:codebuddy=<prefix>/node_modules/@tencent-ai/codebuddy-code
 *
 * and `joycode=<the JoyCoder.joycoder-fe extension directory>` (an unpacked
 * `.vsix` has it under `extension/`).
 *
 * A test whose tool has no entry is skipped; CI runs the byte-exact contract
 * tests instead. A loader for another tool goes here beside Cursor's.
 */

/** The path given for `tool`, or undefined when there is none. */
export function ruleParserBundle(tool: string): string | undefined {
  for (const entry of (process.env.TEAMAI_RULE_PARSER_BUNDLES ?? '').split(path.delimiter)) {
    const at = entry.indexOf('=');
    if (at > 0 && entry.slice(0, at) === tool) return entry.slice(at + 1);
  }
  return undefined;
}

/** The source of the function declaration that starts at `start`, braces matched. */
function functionSource(source: string, start: number): string {
  let depth = 0;
  for (let i = source.indexOf('{', start); i < source.length; i++) {
    if (source[i] === '{') depth++;
    else if (source[i] === '}' && --depth === 0) return source.slice(start, i + 1);
  }
  throw new Error('unbalanced function body');
}

/** The last `function NAME(...)` matching `pattern` before `before`. */
function lastFunctionBefore(source: string, pattern: RegExp, before: number): { name: string; start: number } {
  let found: { name: string; start: number } | undefined;
  for (const match of source.slice(0, before).matchAll(pattern)) found = { name: match[1], start: match.index };
  if (!found) throw new Error(`no function matching ${pattern} in the bundle`);
  return found;
}

export interface CursorRuleParser {
  /** Cursor's `.mdc` frontmatter parse: `{ frontmatter, body }`, or null without frontmatter. */
  parse(text: string): { frontmatter: Record<string, unknown>; body: string } | null;
  /** How Cursor turns `frontmatter.globs` into globs before matching. */
  globs(value: unknown): string[] | undefined;
}

/**
 * Cursor CLI's rule parser, out of `index.js` in a cursor-agent version
 * directory (checked against 2026.09.22 and 2026.09.28). The minified names
 * change per build, so the functions are found by their code: the line
 * parser by its `metadata.disabledEnvironments` keys and `rawFrontmatter`
 * result, its scalar reader by `"true"===`, and the glob splitter by its
 * brace-depth comma split.
 */
export function loadCursorRuleParser(bundle: string): CursorRuleParser {
  const file = fs.statSync(bundle).isDirectory() ? path.join(bundle, 'index.js') : bundle;
  const source = fs.readFileSync(file, 'utf8');

  const parseAt = source.indexOf('rawFrontmatter:`---\\n${');
  if (parseAt < 0) throw new Error(`no Cursor rule parser in ${file}`);
  const parse = lastFunctionBefore(source, /function ([\w$]+)\((\w)\)\{const (\w)=\2\.trimStart\(\);if\(!\3\.startsWith\("---"\)\)return null/g, parseAt);
  const scalar = lastFunctionBefore(source, /function ([\w$]+)\((\w)\)\{const (\w)=\2\.trim\(\);return"true"===\3\|\|"false"!==\3&&/g, parse.start);
  const splitAt = source.search(/if\("\{"===(\w)\)(\w)\+\+;else if\("\}"===\1&&\2>0\)\2--;else if\(","===\1&&0===\2\)/);
  if (splitAt < 0) throw new Error(`no Cursor glob splitter in ${file}`);
  const split = lastFunctionBefore(source, /function ([\w$]+)\((\w)\)\{if\("string"==typeof \2\)/g, splitAt);

  const factory = new Function([
    functionSource(source, scalar.start),
    functionSource(source, parse.start),
    functionSource(source, split.start),
    `return { parse: ${parse.name}, globs: ${split.name} };`,
  ].join('\n'));
  return factory() as CursorRuleParser;
}

export interface CodebuddyRuleParser {
  /** CodeBuddy's read of one rule file: ALWAYS, or MANUAL (path-scoped) with its globs. */
  parse(file: string): Promise<{ type: string; globs: string[] | undefined; alwaysApply: boolean; content: string }>;
}

/** The source of the class method `head` starts, braces matched; `head` must be unique in `source`. */
function methodSource(source: string, head: RegExp, file: string): string {
  const at = source.search(head);
  if (at < 0) throw new Error(`no ${head} in ${file}`);
  return functionSource(source, at);
}

/**
 * CodeBuddy Code's memory parser, out of `dist/codebuddy.js` in the
 * `@tencent-ai/codebuddy-code` package (checked against 2.160.0). WorkBuddy's
 * engine (`dist/codebuddy-lite-wb.mjs`) ships the same parser. The parser
 * class is found by its `scope`/`autoGeneratedGlobs` options and the
 * frontmatter helpers by their names on `MarkdownUtils`, which the build keeps;
 * the module aliases the parser reaches them through are rewritten to locals.
 */
export function loadCodebuddyRuleParser(bundle: string): CodebuddyRuleParser {
  const file = fs.statSync(bundle).isDirectory() ? path.join(bundle, 'dist', 'codebuddy.js') : bundle;
  const source = fs.readFileSync(file, 'utf8');

  const helpers = ['extractFrontMatterWithContent', 'parseListField', 'splitByCommaRespectingBraces']
    .map((name) => methodSource(source, new RegExp(`static ${name}\\(`), file));
  const parse = methodSource(source, /async parse\([\w$]+,[\w$]+\)\{let [\w$]+,\{scope:[\w$]+,autoGeneratedGlobs:/, file);
  const parseGlobs = methodSource(source, /parseGlobs\([\w$]+\)\{if\(![\w$]+\.paths\)return;/, file);
  const local = (code: string): string => code
    .replace(/\(0,[\w$]+\.readFile\)/g, 'readFile')
    .replace(/[\w$]+\.MarkdownUtils\./g, 'MarkdownUtils.')
    .replace(/[\w$]+\.[\w$]+\.(MANUAL|ALWAYS)\b/g, '"$1"');

  const factory = new Function('readFile', [
    `class MarkdownUtils { ${helpers.join('\n')} }`,
    `class Parser { ${local(parse)}\n${local(parseGlobs)} }`,
    'const parser = new Parser();',
    'return { parse: (file) => parser.parse(file, { scope: "project" }) };',
  ].join('\n'));
  return factory(fs.promises.readFile) as CodebuddyRuleParser;
}

export interface JoycodeRuleParser {
  /** JoyCode's read of one `.mdc` project rule (`parseMdcRule`). */
  parse(text: string, filename: string): { globs: string; alwaysApply: boolean; body: string };
  /** Whether JoyCode applies the rule while `file` is the active editor's file, in workspace `cwd`. */
  applies(text: string, filename: string, file: string, cwd: string): boolean;
}

/**
 * A require for the webpack modules of `source`, each evaluated from its own
 * source: a module runs from its `ID(e,t,n){` header to the next one.
 */
function webpackRequire(source: string): (id: string) => Record<string, unknown> {
  const next = /\},\d+\((?:e(?:,t(?:,n)?)?)?\)\{/g;
  const cache = new Map<string, { exports: Record<string, unknown> }>();
  const require = (id: string): Record<string, unknown> => {
    const cached = cache.get(id);
    if (cached) return cached.exports;
    const head = new RegExp(`[{,]${id}\\(((?:e(?:,t(?:,n)?)?)?)\\)\\{`).exec(source);
    if (!head) throw new Error(`no webpack module ${id} in the bundle`);
    const start = head.index + head[0].length;
    next.lastIndex = start;
    const end = next.exec(source);
    if (!end) throw new Error(`no end of webpack module ${id}`);
    const module = { exports: {} as Record<string, unknown> };
    cache.set(id, module);
    const params = head[1] ? head[1].split(',') : [];
    new Function(...params, source.slice(start, end.index + 1).slice(0, -1)).call(module.exports, module, module.exports, require);
    return module.exports;
  };
  return require;
}

/**
 * JoyCode's project-rule reader, out of `dist/extension.js` in the
 * `JoyCoder.joycoder-fe` extension (checked against 3.8.71). `parseMdcRule`
 * and its helpers are found by the getters their module exports them under,
 * and the minimatch JoyCode bundles by its export list. The decision is
 * JoyCode's `collectProjectRuleEntries`: an `alwaysApply` rule applies;
 * otherwise `globs` is split on every comma and each part matched against
 * the file's basename, absolute path and workspace-relative path. The loader
 * fails if the bundle no longer splits that way.
 */
export function loadJoycodeRuleParser(bundle: string): JoycodeRuleParser {
  const file = fs.statSync(bundle).isDirectory() ? path.join(bundle, 'dist', 'extension.js') : bundle;
  const source = fs.readFileSync(file, 'utf8');

  const getter = (name: string): { name: string; at: number } => {
    const match = new RegExp(`get ${name}\\(\\)\\{return ([\\w$]+)\\}`).exec(source);
    if (!match) throw new Error(`no ${name} in ${file}`);
    return { name: match[1], at: match.index };
  };
  const declaration = ({ name, at }: { name: string; at: number }): string => {
    const start = source.indexOf(`function ${name}(`, at);
    if (start < 0) throw new Error(`no function ${name} after its getter in ${file}`);
    return functionSource(source, start);
  };
  const parse = getter('parseMdcRule');
  const factory = new Function([
    declaration(getter('truncateByChars')),
    declaration(getter('extractBodySummary')),
    declaration(parse),
    `return ${parse.name};`,
  ].join('\n'));
  const parseMdcRule = factory() as (text: string, filename: string) => { globs: string; alwaysApply: boolean; body: string };

  if (!/else if\(([\w$]+)\)\{const ([\w$]+)=\1\.split\(","\)\.map\(([\w$]+)=>\3\.trim\(\)\);/.test(source)) {
    throw new Error(`JoyCode no longer splits a rule's globs on every comma in ${file}`);
  }
  const minimatchAt = source.indexOf('t.Minimatch=t.match=t.makeRe=t.braceExpand=');
  const minimatchId = minimatchAt < 0 ? undefined
    : [...source.slice(0, minimatchAt).matchAll(/[{,](\d+)\(e,t,n\)\{"use strict"/g)].pop()?.[1];
  if (!minimatchId) throw new Error(`no bundled minimatch in ${file}`);
  const minimatch = webpackRequire(source)(minimatchId).minimatch as (target: string, pattern: string) => boolean;

  return {
    parse: (text, filename) => {
      const { globs, alwaysApply, body } = parseMdcRule(text, filename);
      return { globs, alwaysApply, body };
    },
    applies: (text, filename, target, cwd) => {
      const { globs, alwaysApply } = parseMdcRule(text, filename);
      if (alwaysApply) return true;
      if (!globs) return false;
      const targets = [path.basename(target), target, path.relative(cwd, target)];
      return globs.split(',').map((glob) => glob.trim())
        .some((glob) => targets.some((candidate) => minimatch(candidate, glob)));
    },
  };
}
