/**
 * OpenClaw / 龙虾-family hook injection (issue #1, 方案二 §四).
 *
 * WorkBuddy (category `lobster`) uses the OpenClaw hook engine — a different
 * shape from Claude's settings.json: a `HOOK.md` (frontmatter `events:`) plus a
 * `handler.ts` placed under `<hooksDir>/teamai-status-report/`. Both shell out to
 * the same `teamai hook-dispatch` entry point, so the reporting core is shared
 * with the Claude/CodeBuddy path; only the trigger adapter differs.
 *
 * Events: `session:start` → session-start dispatch (report + sync);
 *         `command:new`   → prompt-submit dispatch (sync only).
 *
 * NOTE: WorkBuddy's desktop hook config dir (`~/.openclaw/` vs `~/.workbuddy/`)
 * is still pending confirmation (issue §七.1); callers pass the resolved dir.
 */

import path from 'node:path';
import { writeFile, ensureDir, pathExists, remove } from './utils/fs.js';
import { log } from './utils/logger.js';

/** Sub-directory name under <hooksDir> that holds the teamai OpenClaw hook. */
export const OPENCLAW_HOOK_DIR = 'teamai-status-report';

/** Marker so we can recognize (and cleanly remove) our own hook. */
const TEAMAI_MARKER = '[teamai]';

/** Map OpenClaw event → teamai dispatch event. */
const EVENT_MAP: Record<string, string> = {
  'session:start': 'session-start',
  'command:new': 'prompt-submit',
};

function buildHookMd(tool: string): string {
  const events = Object.keys(EVENT_MAP);
  return [
    '---',
    `name: ${TEAMAI_MARKER} status-report`,
    'events:',
    ...events.map((e) => `  - ${e}`),
    `handler: ./handler.ts`,
    '---',
    '',
    `${TEAMAI_MARKER} Reports agent status to the team backend (report/sync/ack) for tool \`${tool}\`.`,
    'Managed by teamai — do not edit by hand.',
    '',
  ].join('\n');
}

function buildHandlerTs(tool: string): string {
  // Map each OpenClaw event to the corresponding teamai dispatch event and shell
  // out. Failures are swallowed so the agent is never blocked.
  const mapLiteral = JSON.stringify(EVENT_MAP);
  return `// ${TEAMAI_MARKER} status-report handler — generated by teamai, do not edit.
import { spawn } from 'node:child_process';

const EVENT_MAP: Record<string, string> = ${mapLiteral};
const TOOL = ${JSON.stringify(tool)};

export default async function handler(ctx: { event?: string } = {}): Promise<void> {
  const dispatchEvent = ctx.event ? EVENT_MAP[ctx.event] : undefined;
  if (!dispatchEvent) return;
  try {
    const child = spawn('teamai', ['hook-dispatch', dispatchEvent, '--tool', TOOL], {
      stdio: ['inherit', 'ignore', 'ignore'],
    });
    child.on('error', () => {});
  } catch {
    // never block the agent
  }
}
`;
}

/**
 * Inject (or refresh) the teamai OpenClaw hook into `<hooksDir>`.
 * Idempotent — rewrites the two files each time.
 */
export async function injectOpenClawHooks(hooksDir: string, tool = 'workbuddy'): Promise<void> {
  const dir = path.join(hooksDir, OPENCLAW_HOOK_DIR);
  await ensureDir(dir);
  await writeFile(path.join(dir, 'HOOK.md'), buildHookMd(tool));
  await writeFile(path.join(dir, 'handler.ts'), buildHandlerTs(tool));
  log.success(`Injected teamai OpenClaw hook into ${dir}`);
}

/** Remove the teamai OpenClaw hook from `<hooksDir>` if present. */
export async function removeOpenClawHooks(hooksDir: string): Promise<void> {
  const dir = path.join(hooksDir, OPENCLAW_HOOK_DIR);
  if (await pathExists(dir)) {
    await remove(dir);
    log.success(`Removed teamai OpenClaw hook from ${dir}`);
  }
}
