/**
 * OpenCode hook injection.
 *
 * Unlike every other agent teamai targets, OpenCode has no settings.json-style
 * shell-command hook list. Instead it auto-loads JS/TS *plugins* — the config
 * loader scans `{plugin,plugins}/*.{ts,js}` under each `.opencode` dir (project
 * scope) and `~/.config/opencode` (user scope). A plugin default-exports a
 * definition with `server` (V1) and `setup` (V2); teamai subscribes to OpenCode's own
 * events and shells out to the same `teamai hook-dispatch` entry point every
 * other agent uses.
 *
 * Event mapping (OpenCode → teamai dispatch), chosen to mirror the Claude
 * built-in hook set as closely as OpenCode's event model allows:
 *   - `session.created`     → session-start  (report / sync / ack)
 *   - `session.idle`        → stop           (update / votes / contribute)
 *   - `chat.message`        → prompt-submit   (track-slash / dashboard)
 *   - `tool.execute.after`  → post-tool-use   (dashboard; matcher-scoped track)
 *
 * The generated plugin is fire-and-forget: OpenCode's `event` hook has no
 * channel to inject a hook's stdout back into the session, so — like the Hermes
 * and OpenClaw adapters — teamai runs the dispatch for its side effects and
 * never blocks the agent. Node's child-process errors are swallowed.
 */

import path from 'node:path';
import { writeFile, writeIfChanged, ensureDir, pathExists, readFileSafe, remove } from './utils/fs.js';
import { probeBinary } from './utils/exec.js';
import { log } from './utils/logger.js';
import { getUserHome } from './utils/home.js';
import { isGitExcludeEnabled, type LocalConfig, type TeamaiConfig } from './types.js';

/** Plugin directory name under an OpenCode config dir. OpenCode scans both
 *  `plugin/` and `plugins/`; we use the singular, matching the docs examples. */
export const OPENCODE_PLUGIN_DIR = 'plugin';

/** Filename of the teamai-managed OpenCode plugin. */
export const OPENCODE_HOOK_FILE = 'teamai-hooks.ts';

/**
 * The file in a project's `.opencode/` that teamai's plugin reads the team MCP
 * servers from on OpenCode V2 (#915): teamai's alone, and kept out of git.
 */
export const OPENCODE_MCP_FILE = 'teamai-mcp.json';

/** A project's `OPENCODE_MCP_FILE`. */
export function opencodeMcpFile(projectRoot: string): string {
  return path.join(projectRoot, '.opencode', OPENCODE_MCP_FILE);
}

/** Marker so `teamai doctor` / `uninstall` can recognize our generated plugin. */
const TEAMAI_MARKER = '[teamai]';

/**
 * Resolve the plugin directory for an OpenCode scope.
 *
 * - project scope: `<baseDir>/.opencode/plugin`
 * - user scope:    `<baseDir>/.config/opencode/plugin`
 *
 * (baseDir is the repo root in project scope and $HOME in user scope, matching
 * how teamai resolves every other OpenCode path.)
 */
export function resolveOpencodePluginDir(baseDir: string, scope: 'project' | 'user'): string {
  const configDir = scope === 'project' ? '.opencode' : path.join('.config', 'opencode');
  return path.join(baseDir, configDir, OPENCODE_PLUGIN_DIR);
}

/**
 * Build the teamai OpenCode plugin source.
 *
 * The plugin subscribes to OpenCode events and shells out to `teamai
 * hook-dispatch <event> --tool opencode [--matcher <m>]`, feeding the same JSON
 * payload on STDIN that every other agent's hooks send (`cwd`, `tool_name`,
 * `tool_input`, `prompt`). It uses Node's `child_process.spawn` with
 * `windowsHide: true` so a missing `teamai` binary or a non-zero exit never
 * surfaces as an error inside the agent session or opens a console window.
 *
 * Two OpenCode-specific bridges are required:
 *   - STDIN payload: hook-dispatch's track / track-slash / todowrite-hint
 *     handlers read `tool_name` / `tool_input` / `prompt` off STDIN, and the
 *     provider-config gate reads `cwd` to pick the project-scope config. Without
 *     a payload those handlers no-op and project gating falls back to the user
 *     config. We forward the plugin's `directory` as `cwd` plus the per-event
 *     fields. For recall attribution (#884) every event also carries the host's
 *     `session_id`, and PostToolUse the tool's output (`tool_response`), a
 *     normalized `tool_status`, and for a `task` call the `session_link` from
 *     the subagent's child session to its parent. `shell.env` names the session
 *     in V1's bash environment (`TEAMAI_AGENT_SESSION_ID`); V2's shell supplies
 *     its native `OPENCODE_SESSION_ID`, read by the same session resolver.
 *   - Tool-id casing: OpenCode passes lowercase tool ids (`skill`, `todowrite`),
 *     but the handler registry keys matchers on Claude's PascalCase names
 *     (`Skill`, `TodoWrite`). We map the id back before dispatching a
 *     matcher-scoped pass.
 */
export function buildPluginSource(userConfigDir = path.join(getUserHome(), '.config', 'opencode')): string {
  return `// ${TEAMAI_MARKER} hooks plugin — generated by teamai, do not edit by hand.
//
// Bridges OpenCode's plugin events to \`teamai hook-dispatch\`, mirroring the
// Claude built-in hook set. Feeds the same STDIN JSON payload other agents send
// so the track / hint handlers and project-scope gating work. Errors are
// swallowed; OpenCode cannot inject a hook's stdout back into the session, so
// this runs the dispatch purely for its side effects (status report / sync /
// update).
//
// NOTE: OpenCode awaits its named hooks (chat.message, tool.execute.after), so
// the dispatch is not truly fire-and-forget for those two — see the timeout
// note below.

/** OpenCode lowercase tool ids → Claude PascalCase matcher names. */
const TOOL_MATCHER = { skill: 'Skill', todowrite: 'TodoWrite' };

/** A host field read defensively: a non-empty string, or undefined. */
const nonEmpty = (value) => (typeof value === 'string' && value ? value : undefined);

/** @param {{ directory?: string, worktree?: string }} ctx */
const TeamaiHooks = async ({ directory, worktree }) => {
  const cwd = directory || worktree;
  // Dispatch one hook event, forwarding a JSON payload on STDIN. \`payload\`
  // fields (cwd / tool_name / tool_input / prompt) match what hook-dispatch's
  // handlers read; \`matcher\` scopes PostToolUse handlers (Skill / TodoWrite).
  const dispatch = async (event, matcher, payload) => {
    try {
      const args = ['hook-dispatch', event, '--tool', 'opencode'];
      if (matcher) {
        args.push('--matcher', matcher);
      }
      const stdin = JSON.stringify({ cwd, ...(payload || {}) });
      const { spawn } = await import('node:child_process');
      await new Promise((resolve) => {
        const child = spawn('teamai', args, {
          shell: process.platform === 'win32',
          windowsHide: true,
          stdio: ['pipe', 'ignore', 'ignore'],
        });
        const finish = () => {
          child.removeListener('error', finish);
          child.removeListener('close', finish);
          resolve();
        };
        child.once('error', finish);
        child.once('close', finish);
        child.stdin.write(stdin);
        child.stdin.end();
      });
    } catch {
      // never block the agent
    }
  };

  return {
    // Lifecycle events name their session in event.properties: sessionID, or
    // on an older host's session.created only the session info.
    event: async ({ event }) => {
      const props = (event && event.properties) || {};
      const session = { session_id: nonEmpty(props.sessionID) || nonEmpty(props.info && props.info.id) };
      if (event.type === 'session.created') {
        await dispatch('session-start', undefined, session);
      } else if (event.type === 'session.idle') {
        await dispatch('stop', undefined, session);
      }
    },
    // A new user message maps to Claude's UserPromptSubmit. The prompt text
    // lives in output.parts (text parts); forward it so track-slash can see
    // slash-command usage.
    'chat.message': async (input, output) => {
      let prompt = '';
      const parts = (output && output.parts) || [];
      for (const part of parts) {
        if (part && part.type === 'text' && typeof part.text === 'string') {
          prompt += part.text;
        }
      }
      await dispatch('prompt-submit', undefined, { session_id: nonEmpty(input && input.sessionID), prompt });
    },
    // Fires after every tool call. Dispatch the wildcard matcher always, plus a
    // matcher-scoped pass so Skill / TodoWrite handlers can fire. input.tool is
    // the lowercase OpenCode tool id; input.args is the tool input; output.output
    // is what the model saw. There is no error flag: only bash reports an exit
    // code, so any other tool's status is unknown. A task call names the
    // child session its subagent ran in, which links it to this session.
    'tool.execute.after': async (input, output) => {
      const tool = (input && input.tool) || '';
      const matcher = TOOL_MATCHER[tool];
      const metadata = (output && output.metadata) || {};
      const exit = tool === 'bash' ? metadata.exit : undefined;
      const payload = {
        session_id: nonEmpty(input && input.sessionID),
        tool_name: matcher || tool,
        tool_input: (input && input.args) || {},
        tool_response: typeof (output && output.output) === 'string' ? output.output : undefined,
        tool_status: typeof exit === 'number' ? (exit === 0 ? 'success' : 'failure') : (output && output.status) || 'unknown',
      };
      const child = tool === 'task' ? nonEmpty(metadata.sessionId) : undefined;
      const parent = nonEmpty(metadata.parentSessionId) || payload.session_id;
      if (child && parent) {
        payload.session_link = { child, parent };
      }
      await dispatch('post-tool-use', undefined, payload);
      if (matcher) {
        await dispatch('post-tool-use', matcher, payload);
      }
    },
    // Names the session in the bash tool's environment, so teamai recall
    // run there records its run under the session its hooks carry.
    'shell.env': async (input, output) => {
      const session = nonEmpty(input && input.sessionID);
      if (session && output && output.env) {
        output.env.TEAMAI_AGENT_SESSION_ID = session;
      }
    },
  };
};

// OpenCode V2 ignores the \`instructions\` entries teamai writes for V1, so the
// V2 setup adds the same files to each request's system prompt: the user
// instruction file and rules, then the nearest project's. It also adds that
// project's team MCP servers, which teamai keeps out of the project's
// opencode.json on V2.
const USER_CONFIG_DIR = ${JSON.stringify(userConfigDir)};

/**
 * The \`.opencode\` directories from \`directory\` up that teamai delivers to:
 * the nearest holding a teamai file. A team with only rules leaves no such
 * file, so then each one with a \`rules\` directory, outermost first, as
 * OpenCode V1 globs teamai's rules entry in each directory up: a member's own
 * \`.opencode/rules\` in a nested package does not hide the team's above it.
 */
const teamaiProjects = async (directory) => {
  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  const exists = (file) => fs.stat(file).then(() => true, () => false);
  const withRules = [];
  for (let dir = directory; dir;) {
    const project = path.join(dir, '.opencode');
    for (const marker of ['teamai-context.md', ${JSON.stringify(OPENCODE_MCP_FILE)}]) {
      if (await exists(path.join(project, marker))) return [project];
    }
    if (await exists(path.join(project, 'rules'))) withRules.unshift(project);
    const parent = path.dirname(dir);
    dir = parent === dir ? undefined : parent;
  }
  return withRules;
};

/** @param {string} directory */
const teamaiContext = async (directory) => {
  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  const read = async (file) => {
    try {
      const text = await fs.readFile(file, 'utf8');
      return text.trim() ? ['Instructions from: ' + file + '\\n' + text] : [];
    } catch {
      return [];
    }
  };
  const rules = async (dir) => {
    let names = [];
    try {
      names = await fs.readdir(dir, { recursive: true });
    } catch {
      return [];
    }
    const texts = [];
    for (const file of names.filter((name) => name.endsWith('.md')).map((name) => path.join(dir, name)).sort()) {
      texts.push(...await read(file));
    }
    return texts;
  };
  const texts = [...await read(path.join(USER_CONFIG_DIR, 'teamai-context.md')), ...await rules(path.join(USER_CONFIG_DIR, 'rules'))];
  for (const project of await teamaiProjects(directory)) {
    texts.push(...await read(path.join(project, 'teamai-context.md')), ...await rules(path.join(project, 'rules')));
  }
  return texts;
};

/**
 * The nearest project's team MCP servers, written in the V1 form opencode.json
 * takes (\`enabled\`), as V2 takes them (\`disabled\`).
 * @param {string} directory
 */
const teamaiMcp = async (directory) => {
  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  const [project] = await teamaiProjects(directory);
  if (!project) return {};
  let servers;
  try {
    servers = JSON.parse(await fs.readFile(path.join(project, ${JSON.stringify(OPENCODE_MCP_FILE)}), 'utf8')).mcp;
  } catch {
    return {};
  }
  const v2 = {};
  for (const [name, server] of Object.entries(servers && typeof servers === 'object' ? servers : {})) {
    if (!server || typeof server !== 'object' || Array.isArray(server)) continue;
    const { enabled, ...config } = server;
    v2[name] = enabled === false ? { ...config, disabled: true } : config;
  }
  return v2;
};

${buildDualPluginDefinition('teamai.hooks', 'TeamaiHooks', 'teamaiContext', 'teamaiMcp')}

`;
}

/**
 * Both hosts load one definition, but call only their own entrypoint.
 * `context` names a function of the session directory returning the texts the
 * V2 setup adds to each request's system prompt, compaction included, and
 * `mcp` one returning the MCP servers it adds to the location; only teamai's
 * own plugin passes them, so an agent-hook plugin adds nothing.
 */
function buildDualPluginDefinition(id: string, factory: string, context?: string, mcp?: string): string {
  const mcpTransform = mcp ? `
    try {
      const servers = await ${mcp}(ctx.location.directory);
      if (Object.keys(servers).length > 0) {
        registrations.push(await ctx.mcp.transform((editor) => {
          for (const [name, config] of Object.entries(servers)) editor.set(name, config);
        }));
      }
    } catch (error) {
      console.error('[teamai] Could not add the team MCP servers', error);
    }` : '';
  const contextHooks = context ? `
    const addContext = async (event) => {
      try {
        if (!Array.isArray(event.system)) return;
        for (const text of await ${context}(ctx.location.directory)) event.system.push({ type: 'text', text });
      } catch (error) {
        console.error('[teamai] Could not add the team rules and instructions', error);
      }
    };
    registrations.push(await ctx.session.hook('context', addContext));
    registrations.push(await ctx.session.hook('compaction', addContext));` : '';
  return `export default {
  id: ${JSON.stringify(id)},
  server: ${factory},
  async setup(ctx) {
    const hooks = await ${factory}({ directory: ctx.location.directory });
    const registrations = [];${contextHooks}${mcpTransform}
    if (hooks['chat.message']) {
      registrations.push(await ctx.session.hook('prompt', async (event) => {
        await hooks['chat.message']({ sessionID: event.sessionID }, { parts: [{ type: 'text', text: event.prompt.text }] });
      }));
    }
    if (hooks['tool.execute.after']) {
      registrations.push(await ctx.tool.hook('execute.after', async (event) => {
        const result = event.status === 'completed' ? event.result : event.error;
        const content = result && result.content;
        const output = event.status === 'error' ? result.message : typeof content === 'string' ? content :
          Array.isArray(content) ? content.filter((part) => part.type === 'text').map((part) => part.text).join('\\n') : undefined;
        const metadata = (result && result.metadata) || {};
        await hooks['tool.execute.after']({
          tool: event.tool === 'shell' ? 'bash' : event.tool === 'subagent' ? 'task' : event.tool,
          sessionID: event.sessionID,
          args: event.input,
        }, {
          output,
          status: event.status === 'error' ? 'failure' : 'success',
          metadata: { ...metadata, sessionId: metadata.sessionID },
        });
      }));
    }
    const controller = new AbortController();
    const events = hooks.event ? (async () => {
      try {
        for await (const event of ctx.event.subscribe({ signal: controller.signal })) {
          const location = event.location || (event.data && event.data.location);
          if (!location || location.directory !== ctx.location.directory) continue;
          await hooks.event({ event: { type: event.type, properties: event.data } });
        }
      } catch (error) {
        if (!controller.signal.aborted) console.error('[teamai] OpenCode event subscription failed', error);
      }
    })() : Promise.resolve();
    return async () => {
      controller.abort();
      await Promise.all(registrations.map((registration) => registration.dispose()));
      await events;
    };
  },
};`;
}

/**
 * Inject (or refresh) the teamai OpenCode plugin for a scope.
 * Idempotent — writes and reports the plugin file only when its content changes.
 */
export async function injectOpencodeHooks(baseDir: string, scope: 'project' | 'user'): Promise<void> {
  const file = path.join(resolveOpencodePluginDir(baseDir, scope), OPENCODE_HOOK_FILE);
  if (await writeIfChanged(file, buildPluginSource())) {
    log.success(`Injected teamai OpenCode hook into ${file}`);
  } else {
    log.debug(`teamai OpenCode hook already up-to-date in ${file}`);
  }
}

let majorVersion: Promise<number> | undefined;

/**
 * OpenCode's major version, from `opencode --version` (`opencode v2.0.24` on
 * V2, `1.18.35` on V1), asked once per run. 1 when the binary is absent or
 * prints no version.
 */
export function opencodeMajorVersion(): Promise<number> {
  return majorVersion ??= probeBinary('opencode').then((output) => {
    const match = /(\d+)\.\d+/.exec(output);
    return match ? Number(match[1]) : 1;
  });
}

/**
 * The teamai plugin in HOME, and whether it is the one this build writes.
 * OpenCode V2 ignores `instructions` and gets the team rules and instruction
 * files only from this plugin's context hook.
 */
export async function opencodeContextPlugin(): Promise<{ file: string; ready: boolean }> {
  const file = path.join(resolveOpencodePluginDir(getUserHome(), 'user'), OPENCODE_HOOK_FILE);
  return { file, ready: await readFileSafe(file) === buildPluginSource() };
}

/**
 * Whether OpenCode gets this project's team content only through teamai's
 * plugin (#915): OpenCode V2, `sharing.gitExclude` on, and the plugin
 * installed as this build writes it. Then the team MCP servers go to
 * `.opencode/teamai-mcp.json` for the plugin, and teamai takes the entries
 * OpenCode V1 reads out of the project's opencode.json files it alone wrote.
 * Otherwise (V1, the setting off, an HTTP-backed team, or no current plugin:
 * removed, skipped, or not written) those entries stay, since without the
 * plugin they are all V2 would get. A pull asks after it reconciled the plugin.
 */
export async function opencodeDeliversThroughPlugin(teamConfig: TeamaiConfig, localConfig: LocalConfig): Promise<boolean> {
  if (localConfig.scope !== 'project' || localConfig.repo.kind === 'http') return false;
  if (!isGitExcludeEnabled(localConfig, teamConfig) || !(await opencodeContextPlugin()).ready) return false;
  return await opencodeMajorVersion() >= 2;
}

/** Remove the teamai OpenCode plugin for a scope if present. */
export async function removeOpencodeHooks(baseDir: string, scope: 'project' | 'user'): Promise<void> {
  const dir = resolveOpencodePluginDir(baseDir, scope);
  const file = path.join(dir, OPENCODE_HOOK_FILE);
  if (await pathExists(file)) {
    await remove(file);
    log.success(`Removed teamai OpenCode hook from ${file}`);
  }
}

/**
 * Reject slugs that could escape the plugin directory when used as a filename.
 * Agent-hook slugs come from the backend command and are not otherwise
 * validated on the OpenCode path (skill / rule slugs go through validateSlug in
 * local-agent), so a slug like `../../evil` would write outside the plugin dir.
 */
function assertSafeSlug(slug: string): void {
  if (!slug || slug.includes('/') || slug.includes('\\') || slug.includes('..') || path.isAbsolute(slug)) {
    throw new Error(`Invalid agent-hook slug: ${slug}`);
  }
}

/** Map Claude PascalCase agent-hook events → OpenCode plugin event dispatch. */
const CLAUDE_TO_OPENCODE_EVENTS: Record<string, string> = {
  SessionStart: 'session.created',
  Stop: 'session.idle',
  UserPromptSubmit: 'chat.message',
  PostToolUse: 'tool.execute.after',
};

/**
 * Build an agent-hook plugin source that runs a fixed shell `command` on a
 * single OpenCode event. Used by the HTTP-source agent-hook pipeline (issue
 * #238) so an enterprise-pushed hook installs as a real OpenCode plugin rather
 * than silently landing in a Claude settings file OpenCode never reads.
 *
 * `matcher` scopes a `tool.execute.after` hook to a single tool (e.g. only run
 * after the Bash tool). OpenCode passes lowercase tool ids while matchers use
 * Claude's PascalCase names, so the generated gate compares case-insensitively.
 * A missing or `*` matcher runs on every tool call. For non-tool events the
 * matcher has no meaning and is ignored.
 */
export function buildAgentHookPluginSource(
  slug: string,
  ocEvent: string,
  command: string,
  matcher?: string,
): string {
  const scoped = ocEvent === 'tool.execute.after' && !!matcher && matcher !== '*';
  let body: string;
  if (ocEvent === 'tool.execute.after') {
    // Tool hook: optionally gate on the tool id (case-insensitive).
    body = scoped
      ? `  return {
    "tool.execute.after": async (input) => {
      const tool = (input && input.tool) || '';
      if (tool.toLowerCase() === ${JSON.stringify(matcher!.toLowerCase())}) { await run(); }
    },
  };`
      : `  return {
    "tool.execute.after": async () => { await run(); },
  };`;
  } else if (ocEvent === 'chat.message') {
    body = `  return {
    "chat.message": async () => { await run(); },
  };`;
  } else {
    // session.* events arrive via the generic `event` hook (event.type).
    body = `  return {
    event: async ({ event }) => {
      if (event.type === ${JSON.stringify(ocEvent)}) { await run(); }
    },
  };`;
  }
  const factory = `TeamaiAgentHook_${slug.replace(/[^A-Za-z0-9_]/g, '_')}`;
  return `// ${TEAMAI_MARKER} agent hook [${slug}] — generated by teamai, do not edit by hand.
const ${factory} = async ({ directory, worktree }) => {
  const run = async () => {
    try {
      const { spawn } = await import('node:child_process');
      await new Promise((resolve) => {
        const windows = process.platform === 'win32';
        const child = spawn(windows ? 'cmd.exe' : 'sh', windows ? ['/d', '/s', '/c', ${JSON.stringify(command)}] : ['-c', ${JSON.stringify(command)}], {
          cwd: directory || worktree,
          windowsHide: true,
          stdio: 'ignore',
        });
        const finish = () => {
          child.removeListener('error', finish);
          child.removeListener('close', finish);
          resolve();
        };
        child.once('error', finish);
        child.once('close', finish);
      });
    } catch {
      // never block the agent
    }
  };
${body}
};

${buildDualPluginDefinition(`teamai.agent.${slug}`, factory)}
`;
}

/**
 * Install a server-pushed agent hook as an OpenCode plugin file.
 * Events with no OpenCode equivalent are logged and skipped.
 */
export async function applyOpencodeAgentHook(def: {
  slug: string;
  event: string;
  command: string;
  baseDir: string;
  scope: 'project' | 'user';
  matcher?: string;
}): Promise<void> {
  assertSafeSlug(def.slug);
  const ocEvent = CLAUDE_TO_OPENCODE_EVENTS[def.event];
  if (!ocEvent) {
    log.warn(`OpenCode does not support event "${def.event}" — skipping hook [${def.slug}]`);
    return;
  }
  const dir = resolveOpencodePluginDir(def.baseDir, def.scope);
  await ensureDir(dir);
  const file = path.join(dir, `teamai-agent-${def.slug}.ts`);
  await writeFile(file, buildAgentHookPluginSource(def.slug, ocEvent, def.command, def.matcher));
  log.success(`Installed OpenCode agent hook [${def.slug}] in ${file}`);
}

/** Remove a server-pushed agent-hook plugin file for OpenCode. */
export async function removeOpencodeAgentHook(opts: {
  slug: string;
  baseDir: string;
  scope: 'project' | 'user';
}): Promise<void> {
  assertSafeSlug(opts.slug);
  const dir = resolveOpencodePluginDir(opts.baseDir, opts.scope);
  const file = path.join(dir, `teamai-agent-${opts.slug}.ts`);
  if (await pathExists(file)) {
    await remove(file);
    log.success(`Removed OpenCode agent hook [${opts.slug}] from ${file}`);
  }
}
