/**
 * OpenCode hook injection.
 *
 * Unlike every other agent teamai targets, OpenCode has no settings.json-style
 * shell-command hook list. Instead it auto-loads JS/TS *plugins* — the config
 * loader scans `{plugin,plugins}/*.{ts,js}` under each `.opencode` dir (project
 * scope) and `~/.config/opencode` (user scope). A plugin is a module exporting a
 * function that returns a `Hooks` object; teamai subscribes to OpenCode's own
 * events and shells out to the same `teamai hook-dispatch` entry point every
 * other agent uses.
 *
 * Event mapping (OpenCode → teamai dispatch), chosen to mirror the Claude
 * built-in hook set as closely as OpenCode's event model allows:
 *   - `session.created`     → session-start  (report / sync / ack)
 *   - `session.idle`        → stop           (update / votes / contribute)
 *   - `chat.message`        → prompt-submit   (track-slash / dashboard)
 *   - `tool.execute.after`  → post-tool-use   (dashboard; matcher-scoped track)
 *
 * The generated plugin is fire-and-forget: OpenCode's `event` hook has no
 * channel to inject a hook's stdout back into the session, so — like the Hermes
 * and OpenClaw adapters — teamai runs the dispatch for its side effects and
 * never blocks the agent. All shell errors are swallowed.
 */

import path from 'node:path';
import { writeFile, ensureDir, pathExists, remove } from './utils/fs.js';
import { log } from './utils/logger.js';

/** Plugin directory name under an OpenCode config dir. OpenCode scans both
 *  `plugin/` and `plugins/`; we use the singular, matching the docs examples. */
export const OPENCODE_PLUGIN_DIR = 'plugin';

/** Filename of the teamai-managed OpenCode plugin. */
export const OPENCODE_HOOK_FILE = 'teamai-hooks.ts';

/** Marker so `teamai doctor` / `uninstall` can recognize our generated plugin. */
const TEAMAI_MARKER = '[teamai]';

/**
 * Resolve the plugin directory for an OpenCode scope.
 *
 * - project scope: `<baseDir>/.opencode/plugin`
 * - user scope:    `<baseDir>/.config/opencode/plugin`
 *
 * (baseDir is the repo root in project scope and $HOME in user scope, matching
 * how teamai resolves every other OpenCode path.)
 */
export function resolveOpencodePluginDir(baseDir: string, scope: 'project' | 'user'): string {
  const configDir = scope === 'project' ? '.opencode' : path.join('.config', 'opencode');
  return path.join(baseDir, configDir, OPENCODE_PLUGIN_DIR);
}

/**
 * Build the teamai OpenCode plugin source.
 *
 * The plugin subscribes to OpenCode events and shells out to `teamai
 * hook-dispatch <event> --tool opencode [--matcher <m>]`. It uses the injected
 * Bun shell (`$`) with `.quiet().nothrow()` so a missing `teamai` binary or a
 * non-zero exit never surfaces as an error inside the agent session.
 */
export function buildPluginSource(): string {
  return `// ${TEAMAI_MARKER} hooks plugin — generated by teamai, do not edit by hand.
//
// Bridges OpenCode's plugin events to \`teamai hook-dispatch\`, mirroring the
// Claude built-in hook set. Fire-and-forget: OpenCode cannot inject a hook's
// stdout back into the session, so this runs the dispatch for its side effects
// (status report / sync / update) and never blocks the agent.

/** @param {{ $: any }} ctx */
export const TeamaiHooks = async ({ $ }) => {
  const dispatch = async (event, matcher) => {
    try {
      const args = ['hook-dispatch', event, '--tool', 'opencode'];
      if (matcher) {
        args.push('--matcher', matcher);
      }
      // .quiet() suppresses output; .nothrow() keeps a non-zero exit (e.g. no
      // teamai on PATH) from throwing into the agent session.
      await $\`teamai \${args}\`.quiet().nothrow();
    } catch {
      // never block the agent
    }
  };

  return {
    event: async ({ event }) => {
      if (event.type === 'session.created') {
        await dispatch('session-start');
      } else if (event.type === 'session.idle') {
        await dispatch('stop');
      }
    },
    // A new user message maps to Claude's UserPromptSubmit.
    'chat.message': async () => {
      await dispatch('prompt-submit');
    },
    // Fires after every tool call. Dispatch the wildcard matcher always, plus
    // the tool name so matcher-scoped handlers (Skill / TodoWrite) can fire.
    'tool.execute.after': async (input) => {
      await dispatch('post-tool-use');
      const tool = input && input.tool;
      if (tool === 'Skill' || tool === 'TodoWrite') {
        await dispatch('post-tool-use', tool);
      }
    },
  };
};
`;
}

/**
 * Inject (or refresh) the teamai OpenCode plugin for a scope.
 * Idempotent — rewrites the plugin file each time.
 */
export async function injectOpencodeHooks(baseDir: string, scope: 'project' | 'user'): Promise<void> {
  const dir = resolveOpencodePluginDir(baseDir, scope);
  await ensureDir(dir);
  const file = path.join(dir, OPENCODE_HOOK_FILE);
  await writeFile(file, buildPluginSource());
  log.success(`Injected teamai OpenCode hook into ${file}`);
}

/** Remove the teamai OpenCode plugin for a scope if present. */
export async function removeOpencodeHooks(baseDir: string, scope: 'project' | 'user'): Promise<void> {
  const dir = resolveOpencodePluginDir(baseDir, scope);
  const file = path.join(dir, OPENCODE_HOOK_FILE);
  if (await pathExists(file)) {
    await remove(file);
    log.success(`Removed teamai OpenCode hook from ${file}`);
  }
}

/** Map Claude PascalCase agent-hook events → OpenCode plugin event dispatch. */
const CLAUDE_TO_OPENCODE_EVENTS: Record<string, string> = {
  SessionStart: 'session.created',
  Stop: 'session.idle',
  UserPromptSubmit: 'chat.message',
  PostToolUse: 'tool.execute.after',
};

/**
 * Build an agent-hook plugin source that runs a fixed shell `command` on a
 * single OpenCode event. Used by the HTTP-source agent-hook pipeline (issue
 * #238) so an enterprise-pushed hook installs as a real OpenCode plugin rather
 * than silently landing in a Claude settings file OpenCode never reads.
 */
export function buildAgentHookPluginSource(slug: string, ocEvent: string, command: string): string {
  const isPromptOrTool = ocEvent === 'chat.message' || ocEvent === 'tool.execute.after';
  // session.* events arrive via the generic `event` hook (event.type); prompt /
  // tool events have their own named hooks.
  const body = isPromptOrTool
    ? `  return {
    ${JSON.stringify(ocEvent)}: async () => { await run(); },
  };`
    : `  return {
    event: async ({ event }) => {
      if (event.type === ${JSON.stringify(ocEvent)}) { await run(); }
    },
  };`;
  return `// ${TEAMAI_MARKER} agent hook [${slug}] — generated by teamai, do not edit by hand.
/** @param {{ $: any }} ctx */
export const TeamaiAgentHook_${slug.replace(/[^A-Za-z0-9_]/g, '_')} = async ({ $ }) => {
  const run = async () => {
    try {
      // .quiet() suppresses output; .nothrow() keeps a non-zero exit from
      // throwing into the agent session. Fire-and-forget — never blocks.
      await $\`sh -c \${${JSON.stringify(command)}}\`.quiet().nothrow();
    } catch {
      // never block the agent
    }
  };
${body}
};
`;
}

/**
 * Install a server-pushed agent hook as an OpenCode plugin file.
 * Events with no OpenCode equivalent are logged and skipped.
 */
export async function applyOpencodeAgentHook(def: {
  slug: string;
  event: string;
  command: string;
  baseDir: string;
  scope: 'project' | 'user';
}): Promise<void> {
  const ocEvent = CLAUDE_TO_OPENCODE_EVENTS[def.event];
  if (!ocEvent) {
    log.warn(`OpenCode does not support event "${def.event}" — skipping hook [${def.slug}]`);
    return;
  }
  const dir = resolveOpencodePluginDir(def.baseDir, def.scope);
  await ensureDir(dir);
  const file = path.join(dir, `teamai-agent-${def.slug}.ts`);
  await writeFile(file, buildAgentHookPluginSource(def.slug, ocEvent, def.command));
  log.success(`Installed OpenCode agent hook [${def.slug}] in ${file}`);
}

/** Remove a server-pushed agent-hook plugin file for OpenCode. */
export async function removeOpencodeAgentHook(opts: {
  slug: string;
  baseDir: string;
  scope: 'project' | 'user';
}): Promise<void> {
  const dir = resolveOpencodePluginDir(opts.baseDir, opts.scope);
  const file = path.join(dir, `teamai-agent-${opts.slug}.ts`);
  if (await pathExists(file)) {
    await remove(file);
    log.success(`Removed OpenCode agent hook [${opts.slug}] from ${file}`);
  }
}
