/**
 * Render a management-backend snapshot into the team-repo layout that every
 * ResourceHandler already reads (`<localPath>/skills/<name>/`, `rules/<name>.md`,
 * `agents/<name>.yaml`, `env/env.yaml`, `hooks/hooks.yaml`, `mcp/mcp.yaml`,
 * `claudemd/<ns>/<name>.md`, `culture.md`, `learnings/<name>.md`, `teamai.yaml`,
 * `tags.yaml`).
 *
 * The server has already resolved org/team/project levels and permission groups
 * for this binding, so the layout is flat: no role/project namespaces to select.
 * This is a port of the reference renderer in the backend (internal/teamaifmt);
 * the two must produce byte-identical trees for the same snapshot.
 */

export interface SnapshotFile {
  path: string;
  sha256: string;
  size: number;
}

export interface SnapshotEntry {
  kind: string;
  name: string;
  namespace?: string;
  level?: string;
  version?: number;
  sha256?: string;
  tags?: string[];
  files?: SnapshotFile[];
  status: 'ok' | 'conflict' | string;
  conflict?: { owners?: string[]; versions?: number[] };
}

/** Merged sharing policy as the server sends it (field names match the backend's JSON). */
export interface SnapshotPolicy {
  enforced_rules?: string[];
  hooks_auto_apply?: boolean;
  hooks_require_team_scripts?: boolean;
  mcp_auto_apply?: boolean;
  mcp_allowed_commands?: string[];
  mcp_allowed_hosts?: string[];
  recall_enabled?: boolean;
  contribute_hint?: boolean;
  co_author?: boolean;
}

export interface ServerSnapshot {
  revision: string;
  generated_at?: string;
  org: { id: string; slug: string; name: string };
  projects: Array<{ id: string; slug: string; name: string; revision?: string }>;
  policy: SnapshotPolicy;
  grants?: Array<{ group_key: string; name: string }>;
  culture?: SnapshotEntry;
  resources: SnapshotEntry[];
  limits?: { max_blob_bytes?: number; max_snapshot_bytes?: number; max_entries?: number };
}

export type BlobReader = (sha256: string) => Promise<Buffer>;

/** Entry file per kind — mirrors resources.Kind.EntryFile on the server. */
export const ENTRY_FILE: Record<string, string> = {
  skill: 'SKILL.md',
  rule: 'RULE.md',
  doc: 'DOC.md',
  agent: 'AGENT.yaml',
  hook: 'HOOK.yaml',
  mcp: 'MCP.yaml',
  env: 'ENV.yaml',
  claudemd: 'CLAUDEMD.md',
  culture: 'CULTURE.md',
  policy: 'POLICY.yaml',
  learning: 'LEARNING.md',
};

async function entryContent(e: SnapshotEntry, read: BlobReader): Promise<Buffer> {
  const want = ENTRY_FILE[e.kind];
  const f = (e.files ?? []).find((x) => x.path === want);
  if (!f) throw new Error(`${e.kind}/${e.name}: missing entry file ${want}`);
  return read(f.sha256);
}

/** YAML double-quoted scalar; the backend uses exactly this escaping. */
export function yamlStr(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function yamlList(items: string[] | undefined): string {
  if (!items || items.length === 0) return '[]';
  return `[${items.map(yamlStr).join(', ')}]`;
}

function yamlBool(b: boolean | undefined): string {
  return b ? 'true' : 'false';
}

function nonComment(line: string): boolean {
  const t = line.trim();
  return t !== '' && !t.startsWith('#');
}

/** ENV.yaml (value / description) → one item of env.yaml. */
function envBlock(key: string, content: string): string {
  const lines = content.split('\n').map((l) => l.replace(/\r$/, ''));
  const secret = lines.some((l) => /^secret:\s*true\s*$/.test(l));
  let out = `  - key: ${key}\n`;
  if (secret) {
    // Secret variables have no value on the server; the member sets it locally.
    out += '    value: ""\n    # secret: 值不在服务端，需在本机设置\n';
  }
  for (const line of lines) {
    if (!nonComment(line) || line.startsWith('secret:')) continue;
    out += `    ${line}\n`;
  }
  return out;
}

/** A top-level YAML mapping → one list item. */
function indentItem(content: string): string {
  let out = '';
  let first = true;
  for (const raw of content.split('\n')) {
    const line = raw.replace(/\r$/, '');
    if (!nonComment(line)) continue;
    out += first ? `  - ${line}\n` : `    ${line}\n`;
    first = false;
  }
  return out;
}

function teamaiYaml(snap: ServerSnapshot, serverUrl: string): string {
  const p = snap.policy ?? {};
  return [
    '# Generated by the teamai management backend on every sync. Do not edit.',
    `team: ${yamlStr(snap.org.slug)}`,
    `description: ${yamlStr(snap.org.name)}`,
    `repo: ${yamlStr(serverUrl)}`,
    'provider: git',
    'mode: server',
    'sharing:',
    `  rules:\n    enforced: ${yamlList(p.enforced_rules)}`,
    `  hooks:\n    autoApply: ${yamlBool(p.hooks_auto_apply)}\n    requireTeamScripts: ${yamlBool(p.hooks_require_team_scripts)}`,
    `  mcp:\n    autoApply: ${yamlBool(p.mcp_auto_apply)}\n    allowedCommands: ${yamlList(p.mcp_allowed_commands)}\n    allowedHosts: ${yamlList(p.mcp_allowed_hosts)}`,
    `  recall:\n    enabled: ${yamlBool(p.recall_enabled)}`,
    `  contributeHint:\n    enabled: ${yamlBool(p.contribute_hint)}`,
    `  coAuthor:\n    enabled: ${yamlBool(p.co_author)}`,
    '',
  ].join('\n');
}

function tagsYaml(snap: ServerSnapshot): string {
  const skills: Record<string, string[]> = {};
  const rules: Record<string, string[]> = {};
  for (const e of snap.resources) {
    if (!e.tags?.length || e.status !== 'ok') continue;
    if (e.kind === 'skill') skills[e.name] = e.tags;
    if (e.kind === 'rule') rules[e.name] = e.tags;
  }
  if (Object.keys(skills).length === 0 && Object.keys(rules).length === 0) return '';
  let out = 'version: 1\n';
  for (const [key, m] of [['skills', skills], ['rules', rules]] as const) {
    const names = Object.keys(m).sort();
    if (names.length === 0) continue;
    out += `${key}:\n`;
    for (const n of names) out += `  ${n}: ${yamlList(m[n])}\n`;
  }
  return out;
}

/**
 * Render the snapshot to a map of relative path → content. Conflicting entries
 * (two bound projects shipping different versions of the same name) are skipped;
 * the caller keeps whatever it already has for them.
 */
export async function renderSnapshot(
  snap: ServerSnapshot,
  read: BlobReader,
  serverUrl: string,
): Promise<Map<string, Buffer>> {
  const out = new Map<string, Buffer>();
  const envVars: string[] = [];
  const hooks: string[] = [];
  const mcps: string[] = [];

  for (const e of snap.resources) {
    if (e.status !== 'ok') continue;
    switch (e.kind) {
      case 'skill':
        for (const f of e.files ?? []) {
          out.set(`skills/${e.name}/${f.path}`, await read(f.sha256));
        }
        break;
      case 'rule':
        out.set(`rules/${e.name}.md`, await entryContent(e, read));
        break;
      case 'doc':
        out.set(`docs/${e.name}`, await entryContent(e, read));
        break;
      case 'agent':
        out.set(`agents/${e.name}.yaml`, await entryContent(e, read));
        break;
      case 'claudemd':
        out.set(`claudemd/${e.namespace || 'common'}/${e.name}.md`, await entryContent(e, read));
        break;
      case 'learning':
        out.set(`learnings/${e.name}.md`, await entryContent(e, read));
        break;
      case 'env':
        envVars.push(envBlock(e.name, (await entryContent(e, read)).toString('utf8')));
        break;
      case 'hook':
        hooks.push(indentItem((await entryContent(e, read)).toString('utf8')));
        for (const f of e.files ?? []) {
          if (f.path.startsWith('scripts/')) out.set(`hooks/${f.path}`, await read(f.sha256));
        }
        break;
      case 'mcp':
        mcps.push(indentItem((await entryContent(e, read)).toString('utf8')));
        break;
      default:
        // policy is folded into teamai.yaml; unknown kinds are ignored on purpose so
        // an older CLI keeps working against a newer server.
        break;
    }
  }

  if (envVars.length) out.set('env/env.yaml', Buffer.from(`variables:\n${envVars.join('')}`));
  if (hooks.length) out.set('hooks/hooks.yaml', Buffer.from(`hooks:\n${hooks.join('')}`));
  if (mcps.length) out.set('mcp/mcp.yaml', Buffer.from(`servers:\n${mcps.join('')}`));
  if (snap.culture) out.set('culture.md', await entryContent(snap.culture, read));
  out.set('teamai.yaml', Buffer.from(teamaiYaml(snap, serverUrl)));
  const tags = tagsYaml(snap);
  if (tags) out.set('tags.yaml', Buffer.from(tags));
  return out;
}
